apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hpcc-efs
  namespace: default
spec:
  releaseName: efsstorage
  chart:
    git: https://github.com/hpcc-systems/helm-chart
    ref: master
    version: 0.1.0
    path: helm/examples/efs/hpcc-efs
    #secretRef:  # not required for public repo
    #  name: git-https-credentials
  values:
    efs:
      namespace: default
      region: us-east-1 
      id: fs-739f91f3
